image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - Build
  - Deploy

build_image:
  stage: Build
  tags:
    - docker
  script:
    - docker build -t passwd .
    - docker image push $REGISTRY_URL/passwd:latest
  only:
    - master

deploy_image:
  stage: Deploy
  tags:
    - ssh
  script:
    - docker pull $REGISTRY_URL/passwd:latest
    - docker run -p 3000:3000 --name passwd -e DATABASE_URL="$DATABASE_URL" -e SECRET_KEY="$SECRET_KEY" passwd:latest
  only:
    - master
