image: docker:latest

services:
  - docker:dind

stages:
  - Build

test_build:
  stage: Build
  script:
    - docker ps
    - docker build -t passwd .
    - docker image push 192.168.1.108:5000/passwd:latest
