image: docker:latest
variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  # DOCKER_TLS_CERTDIR: "/certs"
  # IMAGE_NAME: image_name

services:
  - docker:dind

stages:
  - Build

test_build:
  stage: Build
  script:
    - docker ps
    - docker build -t passwd .
    - docker image push 192.168.1.108:5000/passwd:latest
  only:
    - master
