table! {
    use diesel::sql_types::*;

    /// Representation of the `passwords` table.
    ///
    /// (Automatically generated by Diesel.)
    passwords (id) {
        /// The `id` column of the `passwords` table.
        ///
        /// Its SQL type is `Unsigned<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Unsigned<Integer>,
        /// The `key` column of the `passwords` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Varchar,
        /// The `value` column of the `passwords` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Varchar,
        /// The `length` column of the `passwords` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        length -> Integer,
        /// The `type` column of the `passwords` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "type"]
        type_ -> Varchar,
        /// The `user_id` column of the `passwords` table.
        ///
        /// Its SQL type is `Unsigned<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Unsigned<Integer>,
        /// The `created_at` column of the `passwords` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamp,
        /// The `updated_at` column of the `passwords` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamp,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Unsigned<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Unsigned<Integer>,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `salt` column of the `users` table.
        ///
        /// Its SQL type is `Blob`.
        ///
        /// (Automatically generated by Diesel.)
        salt -> Blob,
        /// The `password` column of the `users` table.
        ///
        /// Its SQL type is `Blob`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Blob,
    }
}

allow_tables_to_appear_in_same_query!(passwords, users,);
